### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by linakherchi** [AlexArchibeque/Fwitch#3]
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-in-person/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

**Comment by linakherchi** [comment]
MVP List needs more work: 

- 3 of your MVPs should be User Auth, Heroku and Production ReadME. Could you please add Heroku + Production ReadME ? 
- A description sentence of the app is needed.
- What will be your CRUD MVP?
- Ability to set categories for searching in MVP 1 should have its own MVP as you will have to create categories.
- I would love to see more descriptive MVPs.

Would be happy to discuss it further!

**Comment by AlexArchibeque** [comment]
Hey Lina, I went ahead and redid my MVP List. Unsure If it is too many, too detailed/under detailed etc. 

I do not understand the idea behind a CRUD feature. If there was one it would be the Clips feature as you would be able to upload(create) videos, update the videos, delete the videos, and watch the videos. But not sure if my thought process is correct behind that.

Thanks for the feedback.

**Comment by linakherchi** [comment]
Yes ! Correct - Because you will be able to create, watch, update, and delete videos, that accounts for a full CRUD feature.

Thanks for the updates!
