### ISSUE TITLE
Sample State 

### ISSUE THREAD

**Issue by linakherchi** [AlexArchibeque/Fwitch#4]
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by linakherchi** [comment]
Thanks, Alex ! 

1) Could you please explain the messages key that holds an array of IDs? What are these IDs pointing you. Also, it is highly preferable to store foreign keys rather than arrays in your state shape. 
2) State shape foreign keys and columns with `_` need to be camelCased.
3) You want to refer to `video_id`/`private_chat_id` as `id` so that you are able to differentiate between primary keys and foreign keys.
4) You also need an `id` in the follows slice of state.
5) Need a channels slice of state, unless you thought of channels as privateChats, in which case, please just change the name to reflect the table name that you have in the schema

Let me know if you have any questions

**Comment by AlexArchibeque** [comment]
Hey Lina, I've went ahead and updated a few things.

I changed privateChats to messages as well as added it to the schema, which will retrieve messages based who who you are logged in as and show them in order hence the arrays. 

Not sure how I would organize messages so that they would appear in order without two arrays at the moment.

Went ahead and changed all the foreign keys and columns to camelCased, as well as changing non-foreign key ID's to the name of id, follows id has also been added.

Thanks for all the feedback it makes me rethink a lot of what is needed and what things do.

**Comment by linakherchi** [comment]
1) How do you handle the difference between channel messages and direct messages? I am thinking of having a channel messages and direct messages tables. How would you handle group messages ? Are you thinking of implementing these on the first hand ? 

(Are there even direct messages on Twitch?)

I highly recommend you looking at old Twitch clone wikis to have some inspiration

**Comment by AlexArchibeque** [comment]
There are private messages and that is the implementation of messages are trying to mimic, the exact implementation is a little foggy but my idea is:

If you are logged in,
 can start a private message session with another user, 
 history with that user will be saved with your username/date/time.

In terms of chatbox messages I would want to make a different implementation for them not including the backend as I would not like to store them and instead have a maximum amount for each channel that then refreshes anytime you come into chat, maybe using some sort of local storage or other implementation.

I will look more deeply into old twitch clones for inspiration.

**Comment by linakherchi** [comment]
I would love to learn more about how you'd like to implement channel messages. Let me know if you want to meet. We can also discuss it further once you reach direct and channel messages.
