### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by linakherchi** [AlexArchibeque/Fwitch#6]
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by linakherchi** [comment]
Thanks ! 

Routes need to be `back_ticked`.

**Comment by AlexArchibeque** [comment]
Gave back ticks to all of my routes, Thanks Lina
